-- seed-places.sql: up to 95 starter places (places you already added yourself are skipped) (16 each for Waterfall, Mountain, Beach, Lake and Forest, 15 for Culture).
-- Run ONCE in the Supabase SQL editor AFTER schema.sql, after you have signed in with your admin Google account
-- and added yourself to public.admins. Safe to re-run (existing places are skipped).
-- Places start as DRAFT with no photo. In /admin.html tap "Add photos to new places": each place gets a real
-- Unsplash photo (with credit) and is published automatically. Entry fees are left as "check before you go".
do $$
declare owner uuid;
begin
  select u.id into owner from auth.users u join public.admins a on a.email = lower(u.email) order by a.email limit 1;
  if owner is null then
    raise exception 'Sign in to TerraLens with your admin Google account first, and add that email to public.admins.';
  end if;
  insert into public.profiles (id) values (owner) on conflict (id) do nothing;

  insert into public.places (name, slug, category, country, region, city, latitude, longitude, best_season, best_time, description,
                             entry_fee, access_info, status, created_by)
  select v.name, v.slug, v.category, v.country, v.region, v.city, v.latitude, v.longitude, v.best_season, v.best_time, v.description,
         'Varies. Check before you go.', 'Check access, opening times and conditions locally before travelling.', 'draft', owner
  from (values
  ('Victoria Falls','victoria-falls','Waterfall','Zimbabwe','Matabeleland North','Victoria Falls',-17.9243,25.8572,'February to May for the biggest flow; September to December for clearer views','Morning, when the light is soft and crowds are small','A curtain of water nearly 1.7 km wide where the Zambezi River drops into a narrow gorge on the Zimbabwe-Zambia border. The spray rises high enough to be seen from far away.'),
  ('Iguazu Falls','iguazu-falls','Waterfall','Argentina','Misiones','Puerto Iguazu',-25.6953,-54.4367,'March to May and August to November','Morning, when the light is soft and crowds are small','A vast system of about 270 waterfalls across the Argentina-Brazil border, set in subtropical rainforest. The Devil''s Throat is the most powerful drop.'),
  ('Niagara Falls','niagara-falls','Waterfall','Canada','Ontario','Niagara Falls',43.0962,-79.0377,'May to October','Morning, when the light is soft and crowds are small','Three famous waterfalls on the Niagara River at the border of Canada and the United States. Boat tours and walkways take visitors right up to the spray.'),
  ('Angel Falls','angel-falls','Waterfall','Venezuela','Bolivar','Canaima National Park',5.9701,-62.5362,'June to December, when rain gives fuller flow','Morning, when the light is soft and crowds are small','The world''s tallest uninterrupted waterfall, falling from a flat-topped tepui in Canaima National Park. It is reached by river and a jungle trek.'),
  ('Kaieteur Falls','kaieteur-falls','Waterfall','Guyana','Potaro-Siparuni','Kaieteur National Park',5.1753,-59.4813,'May to August and November to January','Morning, when the light is soft and crowds are small','One of the world''s largest single-drop waterfalls by volume, on the Potaro River. It is usually reached by a short flight from Georgetown.'),
  ('Gullfoss','gullfoss','Waterfall','Iceland','Southern','Haukadalur',64.3271,-20.1199,'June to August for long days; winter for ice and snow','Morning, when the light is soft and crowds are small','A two-tier waterfall on the Hvita River that plunges into a rugged canyon. It is a main stop on Iceland''s Golden Circle route.'),
  ('Seljalandsfoss','seljalandsfoss','Waterfall','Iceland','Southern','Hvolsvollur',63.6156,-19.9886,'May to September','Morning, when the light is soft and crowds are small','A slender waterfall that drops over an old sea cliff, with a path that lets you walk behind the falling water. Evening light is a favourite for photographers.'),
  ('Skogafoss','skogafoss','Waterfall','Iceland','Southern','Skogar',63.5321,-19.5114,'May to September','Morning, when the light is soft and crowds are small','A powerful waterfall about 60 metres high and 25 metres wide on Iceland''s south coast, often with a rainbow in the spray. Stairs lead to a viewing platform at the top.'),
  ('Krka Waterfalls','krka-waterfalls','Waterfall','Croatia','Sibenik-Knin','Skradin',43.8039,15.9708,'April to June and September','Morning, when the light is soft and crowds are small','A series of cascades and travertine barriers in Krka National Park, crossed by wooden walkways. Swimming rules change, so check the park''s current guidance.'),
  ('Ban Gioc-Detian Falls','ban-gioc-detian-falls','Waterfall','Vietnam','Cao Bang','Trung Khanh',22.8556,106.7194,'September to October','Morning, when the light is soft and crowds are small','A broad, stepped waterfall on the Quay Son River that forms part of the border between Vietnam and China. Rice fields and limestone hills surround it.'),
  ('Kuang Si Falls','kuang-si-falls','Waterfall','Laos','Luang Prabang','Luang Prabang',19.7525,101.9878,'November to April','Morning, when the light is soft and crowds are small','A tiered waterfall with turquoise pools near Luang Prabang, ending in a tall cascade. Forest trails lead to the top, and a bear rescue centre sits near the entrance.'),
  ('Jog Falls','jog-falls','Waterfall','India','Karnataka','Shimoga',14.2294,74.8125,'July to September (monsoon)','Morning, when the light is soft and crowds are small','One of India''s highest plunge waterfalls, where the Sharavathi River drops in several streams. It is at its most dramatic after heavy monsoon rain.'),
  ('Yosemite Falls','yosemite-falls','Waterfall','United States','California','Yosemite National Park',37.7569,-119.5963,'April to June','Morning, when the light is soft and crowds are small','North America''s tallest waterfall, falling in three sections from the rim of Yosemite Valley. Flow is strongest in spring and can dry up by late summer.'),
  ('Ouzoud Falls','ouzoud-falls','Waterfall','Morocco','Beni Mellal-Khenifra','Azilal',32.0147,-6.7195,'March to June','Morning, when the light is soft and crowds are small','Tiered waterfalls about 110 metres high in the Middle Atlas mountains, with olive groves and wild macaques along the paths. Boat rides run at the base.'),
  ('Lobe Falls','lobe-falls','Waterfall','Cameroon','South','Kribi',2.88,9.9,'December to February (dry season)','Morning, when the light is soft and crowds are small','A rare waterfall that tumbles over rocks straight into the Atlantic Ocean near Kribi. Local guides take visitors by pirogue to see the falls from the water.'),
  ('Tugela Falls','tugela-falls','Waterfall','South Africa','KwaZulu-Natal','Royal Natal National Park',-28.7525,28.8992,'December to March, after summer rain','Morning, when the light is soft and crowds are small','One of the tallest waterfalls in the world, tumbling in five drops from the Drakensberg escarpment. A hike from the Sentinel car park leads to the top.'),
  ('Mount Kilimanjaro','mount-kilimanjaro','Mountain','Tanzania','Kilimanjaro','Moshi',-3.0674,37.3556,'January to March and June to October','Sunrise','Africa''s highest peak, a freestanding volcano rising to 5,895 metres. Several routes lead to the summit, which walkers can reach without technical climbing.'),
  ('Mount Fuji','mount-fuji','Mountain','Japan','Yamanashi and Shizuoka','Fujinomiya',35.3606,138.7274,'Early July to early September for climbing','Sunrise','Japan''s highest mountain at 3,776 metres, a near-perfect volcanic cone that is sacred in Japanese culture. The official climbing season is short.'),
  ('Matterhorn','matterhorn','Mountain','Switzerland','Valais','Zermatt',45.9763,7.6586,'June to September for hiking; December to March for skiing','Sunrise','A pyramid-shaped peak on the Swiss-Italian border and one of the most recognisable mountains in the Alps. Zermatt is the main base for visitors.'),
  ('Everest Base Camp','everest-base-camp','Mountain','Nepal','Solukhumbu','Lukla',28.0026,86.8528,'April to May and October to November','Sunrise','A famous high-altitude trek through Sherpa villages to the foot of the world''s highest mountain. Altitude sickness is a real risk, so allow time to acclimatise.'),
  ('Denali','denali','Mountain','United States','Alaska','Denali National Park',63.0692,-151.007,'June to August','Sunrise','North America''s highest peak at 6,190 metres, rising above wild tundra in Denali National Park. The park road offers wildlife and mountain views.'),
  ('Torres del Paine','torres-del-paine','Mountain','Chile','Magallanes','Puerto Natales',-50.9423,-73.4068,'November to March','Sunrise','Granite towers, glaciers and turquoise lakes in Patagonia. The W and O circuit treks are among South America''s most famous hikes, in very changeable weather.'),
  ('Mount Cameroon','mount-cameroon','Mountain','Cameroon','Southwest','Buea',4.2033,9.1706,'November to April (dry season)','Sunrise','The highest peak in West and Central Africa at about 4,040 metres, an active volcano rising from the Atlantic coast. The annual Race of Hope climbs it from Buea.'),
  ('Table Mountain','table-mountain','Mountain','South Africa','Western Cape','Cape Town',-33.9628,18.4098,'October to March','Sunrise','A flat-topped mountain overlooking Cape Town and the Atlantic. Visitors hike one of several trails or ride the cable car, which closes in strong wind.'),
  ('Tre Cime di Lavaredo','tre-cime-di-lavaredo','Mountain','Italy','South Tyrol and Veneto','Auronzo',46.619,12.302,'June to September','Sunrise','Three dramatic limestone peaks in the Dolomites, ringed by an easy and popular loop trail. Mountain huts along the route serve meals with the peaks in view.'),
  ('Mount Rainier','mount-rainier','Mountain','United States','Washington','Mount Rainier National Park',46.8523,-121.7603,'July to September','Sunrise','A glaciated volcano of 4,392 metres south-east of Seattle, surrounded by wildflower meadows in summer. Paradise and Sunrise are the main viewpoints.'),
  ('Mount Kenya','mount-kenya','Mountain','Kenya','Central','Nanyuki',-0.1521,37.3084,'January to February and August to September','Sunrise','Africa''s second-highest mountain, with jagged glaciated peaks right on the equator. Trekkers cross moorland, forest and alpine zones to reach Point Lenana.'),
  ('Annapurna Circuit','annapurna-circuit','Mountain','Nepal','Gandaki','Pokhara',28.5961,83.8203,'March to May and October to November','Sunrise','A classic Himalayan trek that crosses the high Thorong La pass and passes through varied valleys and villages. It can also be hiked in sections.'),
  ('Mount Bromo','mount-bromo','Mountain','Indonesia','East Java','Probolinggo',-7.9425,112.953,'April to October','Sunrise','An active volcano in a vast sandy caldera, best visited at sunrise from the Penanjakan viewpoint. Expect fine volcanic dust and cold early mornings.'),
  ('Huangshan','huangshan','Mountain','China','Anhui','Huangshan City',30.133,118.17,'April to May and September to November','Sunrise','The Yellow Mountains are known for granite peaks, twisted pines and seas of cloud. Stone staircases and cable cars make the summits reachable.'),
  ('Mount Toubkal','mount-toubkal','Mountain','Morocco','Marrakech-Safi','Imlil',31.059,-7.9161,'April to June and September to October','Sunrise','The highest peak in North Africa at 4,167 metres, reached from the Berber village of Imlil in the High Atlas. It is a demanding but non-technical hike in summer.'),
  ('Fitz Roy','fitz-roy','Mountain','Argentina','Santa Cruz','El Chalten',-49.2711,-72.9553,'December to March','Sunrise','A sharp granite spire that dominates the skyline of El Chalten in Patagonia. Day hikes lead to Laguna de los Tres, with views of the peak at sunrise.'),
  ('Grace Bay','grace-bay','Beach','Turks and Caicos','Providenciales','Grace Bay',21.794,-72.18,'December to April','Late afternoon','A long stretch of soft white sand and shallow turquoise water protected by a barrier reef. Calm conditions make it good for swimming and snorkelling.'),
  ('Anse Source d''Argent','anse-source-d-argent','Beach','Seychelles','La Digue','La Digue',-4.3721,55.828,'April to May and October to November','Late afternoon','A famous beach framed by smooth granite boulders and shallow lagoons. Visit at low tide and in the morning for the best light and calm water.'),
  ('Whitehaven Beach','whitehaven-beach','Beach','Australia','Queensland','Whitsunday Island',-20.2827,149.0383,'September to November','Late afternoon','Seven kilometres of pure white silica sand on Whitsunday Island. The swirling sand and water patterns at Hill Inlet are best seen from the lookout.'),
  ('Navagio Beach','navagio-beach','Beach','Greece','Ionian Islands','Zakynthos',37.8597,20.6247,'May to September','Late afternoon','A secluded cove with white sand and tall cliffs, known for a shipwreck on the shore. It is reached by boat, and the cliff viewpoint above gives the classic photo.'),
  ('Praia das Catedrais','praia-das-catedrais','Beach','Spain','Galicia','Ribadeo',43.5527,-7.1561,'June to September, at low tide','Late afternoon','A beach lined with towering rock arches carved by the sea. It can only be explored safely at low tide, so check tide times and book ahead in summer.'),
  ('Bondi Beach','bondi-beach','Beach','Australia','New South Wales','Sydney',-33.8908,151.2743,'November to March','Late afternoon','Sydney''s best-known beach, with surf, an ocean pool and a coastal walk to Coogee. Lifeguards patrol the flagged areas, so swim between the flags.'),
  ('Railay Beach','railay-beach','Beach','Thailand','Krabi','Railay',8.0116,98.8372,'November to April','Late afternoon','A beach on a peninsula reachable only by boat, framed by limestone cliffs popular with rock climbers. Phra Nang Beach nearby has a cave shrine.'),
  ('Matira Beach','matira-beach','Beach','French Polynesia','Society Islands','Bora Bora',-16.53,-151.745,'May to October','Late afternoon','A long public beach on Bora Bora with calm, clear shallows and views of Mount Otemanu. It is one of the island''s most accessible places to swim.'),
  ('Kribi Beach','kribi-beach','Beach','Cameroon','South','Kribi',2.9404,9.9102,'December to February','Late afternoon','Palm-fringed sand on the Atlantic coast of Cameroon, known for fresh seafood and a relaxed atmosphere. Fishing pirogues work from the shore in the morning.'),
  ('Limbe Down Beach','limbe-down-beach','Beach','Cameroon','Southwest','Limbe',4.0186,9.2062,'December to February','Late afternoon','A black volcanic sand beach in Limbe with Mount Cameroon rising behind it. Fishermen land their catch here and grilled fish is sold nearby.'),
  ('Copacabana Beach','copacabana-beach','Beach','Brazil','Rio de Janeiro','Rio de Janeiro',-22.9711,-43.1822,'December to March','Late afternoon','Four kilometres of city beach beside a famous black-and-white wave-pattern promenade. Early mornings are quieter and weekends are lively.'),
  ('Camps Bay','camps-bay','Beach','South Africa','Western Cape','Cape Town',-33.95,18.378,'November to March','Late afternoon','A wide white-sand beach beneath the Twelve Apostles mountains, with palm trees and cafes behind. The Atlantic water is cold, but the sunsets are superb.'),
  ('White Beach, Boracay','white-beach-boracay','Beach','Philippines','Western Visayas','Boracay',11.965,121.923,'November to May','Late afternoon','A four-kilometre white-sand beach with calm water, watersports and lively evenings. Different stretches suit quiet or social tastes.'),
  ('Diani Beach','diani-beach','Beach','Kenya','Kwale','Diani',-4.31,39.58,'December to March and July to October','Late afternoon','A long coral-sand beach on Kenya''s south coast, with palm trees and warm Indian Ocean water. Snorkelling and kite surfing are popular.'),
  ('Nungwi Beach','nungwi-beach','Beach','Tanzania','Zanzibar','Nungwi',-5.725,39.299,'June to October and December to February','Late afternoon','A beach at the northern tip of Zanzibar with clear water and traditional dhow building nearby. Tides change the shoreline a lot, so check them.'),
  ('Tulum Beach','tulum-beach','Beach','Mexico','Quintana Roo','Tulum',20.2114,-87.4654,'November to April','Late afternoon','A white-sand beach below Mayan ruins on the Caribbean coast. Visit early to avoid crowds, and use reef-safe sunscreen.'),
  ('Lake Louise','lake-louise','Lake','Canada','Alberta','Banff National Park',51.4254,-116.1773,'June to September; winter for skating','Early morning for calm water','A glacier-fed lake of striking turquoise colour in Banff National Park, surrounded by peaks. Trails lead to teahouses and viewpoints above the water.'),
  ('Moraine Lake','moraine-lake','Lake','Canada','Alberta','Banff National Park',51.3217,-116.186,'June to September','Early morning for calm water','A deep blue lake in the Valley of the Ten Peaks, famous from the Rockpile viewpoint. Access is by shuttle in the main season, so plan ahead.'),
  ('Lake Como','lake-como','Lake','Italy','Lombardy','Como',46.016,9.257,'April to October','Early morning for calm water','A long, deep Alpine lake with villas, gardens and mountain-backed villages. Ferries link towns such as Bellagio, Varenna and Menaggio.'),
  ('Lake Garda','lake-garda','Lake','Italy','Veneto and Lombardy','Sirmione',45.6,10.67,'April to October','Early morning for calm water','Italy''s largest lake, with lemon groves, castles and lively waterfront towns. The north is mountainous and windy, with good sailing and windsurfing.'),
  ('Lake Bled','lake-bled','Lake','Slovenia','Upper Carniola','Bled',46.3639,14.0938,'May to September','Early morning for calm water','A glacial lake with a tiny island church and a clifftop castle. A traditional pletna boat carries visitors to the island.'),
  ('Plitvice Lakes','plitvice-lakes','Lake','Croatia','Lika-Senj','Plitvica',44.8654,15.582,'April to October','Early morning for calm water','Sixteen terraced lakes joined by waterfalls and wooden walkways inside a national park. Colours change with minerals and light, and it is busy in summer.'),
  ('Lake Geneva','lake-geneva','Lake','Switzerland','Vaud','Lausanne',46.45,6.53,'May to September','Early morning for calm water','A crescent-shaped lake shared by Switzerland and France, with vineyards, castles and Alpine views. Lake steamers connect the shoreline towns.'),
  ('Lake Titicaca','lake-titicaca','Lake','Peru','Puno','Puno',-15.8402,-70.0219,'April to October','Early morning for calm water','One of the highest large navigable lakes in the world, shared by Peru and Bolivia. Visit the reed islands of the Uros people and Taquile Island.'),
  ('Lake Kivu','lake-kivu','Lake','Rwanda','Western Province','Rubavu',-1.68,29.25,'June to September','Early morning for calm water','A calm lake in the Rwandan highlands with islands, hot springs and lakeside towns such as Rubavu and Kibuye. Kayaking and boat trips are popular.'),
  ('Crater Lake','crater-lake','Lake','United States','Oregon','Crater Lake National Park',42.9446,-122.109,'July to September','Early morning for calm water','The deepest lake in the United States, filling the caldera of a collapsed volcano with intensely blue water. Rim Drive circles the lake with many viewpoints.'),
  ('Lake Tekapo','lake-tekapo','Lake','New Zealand','Canterbury','Tekapo',-44.005,170.476,'October to April','Early morning for calm water','A turquoise glacial lake in a dark-sky reserve. The Church of the Good Shepherd sits on the shore, and lupins bloom nearby in late spring.'),
  ('Lake Atitlan','lake-atitlan','Lake','Guatemala','Solola','Panajachel',14.687,-91.202,'November to April','Early morning for calm water','A volcano-ringed lake in the Guatemalan highlands with Mayan villages on its shores. Small boats run between the towns, each with its own character.'),
  ('Lake Malawi','lake-malawi','Lake','Malawi','Southern Region','Cape Maclear',-14.019,34.834,'May to October','Early morning for calm water','A vast freshwater lake, home to hundreds of colourful cichlid fish, with sandy bays and islands. Snorkelling and kayaking are popular at Cape Maclear.'),
  ('Lake Bosumtwi','lake-bosumtwi','Lake','Ghana','Ashanti','Abono',6.5,-1.4167,'November to March','Early morning for calm water','A near-circular crater lake formed by a meteorite impact, sacred to the Ashanti people. Forested hills and fishing villages surround the water.'),
  ('Lake Barombi Mbo','lake-barombi-mbo','Lake','Cameroon','Southwest','Kumba',4.66,9.4,'November to March','Early morning for calm water','A deep crater lake near Kumba, ringed by rainforest and known for fish found nowhere else. Local guides lead walks and canoe trips.'),
  ('Pangong Lake','pangong-lake','Lake','India','Ladakh','Pangong',33.75,78.67,'May to September','Early morning for calm water','A high-altitude lake in the Himalayas whose water shifts between blue, green and grey through the day. Permits are required and the altitude demands acclimatisation.'),
  ('Amazon Rainforest','amazon-rainforest','Forest','Brazil','Amazonas','Manaus',-3.119,-60.0217,'June to November (drier months)','Morning','The largest tropical rainforest on Earth, with rivers, wildlife and Indigenous communities. Many visitors explore by boat or jungle lodge from Manaus.'),
  ('Black Forest','black-forest','Forest','Germany','Baden-Württemberg','Freiburg',48.0,8.2,'May to October','Morning','A wooded mountain range of dark spruce and fir, known for hiking trails, lakes such as Titisee and traditional villages. Cuckoo clocks and cherry cake are local traditions.'),
  ('Daintree Rainforest','daintree-rainforest','Forest','Australia','Queensland','Daintree',-16.17,145.418,'May to September','Morning','One of the oldest rainforests in the world, meeting the Great Barrier Reef at Cape Tribulation. Rare plants, cassowaries and river cruises are highlights.'),
  ('Bwindi Impenetrable Forest','bwindi-impenetrable-forest','Forest','Uganda','Kanungu','Buhoma',-1.05,29.67,'June to August and December to February','Morning','An ancient mountain rainforest that shelters around half of the world''s mountain gorillas. Visits are strictly permit-controlled and led by trained guides.'),
  ('Hoh Rain Forest','hoh-rain-forest','Forest','United States','Washington','Olympic National Park',47.86,-123.934,'July to September','Morning','A temperate rainforest draped in moss, with giant spruce and hemlock trees. Short loop trails make it easy to walk among the old growth.'),
  ('Bialowieza Forest','bialowieza-forest','Forest','Poland','Podlaskie','Bialowieza',52.7,23.87,'May to September','Morning','One of the last primeval lowland forests in Europe, on the Poland-Belarus border and home to wild European bison. Guided walks are available.'),
  ('Arashiyama Bamboo Grove','arashiyama-bamboo-grove','Forest','Japan','Kyoto','Kyoto',35.0094,135.6672,'March to May and November to December','Morning','A path through towering bamboo that creaks and sways in the wind, in western Kyoto. Go early in the morning for quiet and soft light.'),
  ('Monteverde Cloud Forest','monteverde-cloud-forest','Forest','Costa Rica','Puntarenas','Monteverde',10.3,-84.8,'December to April','Morning','A misty mountain forest rich in orchids, hummingbirds and, with luck, the resplendent quetzal. Hanging bridges and canopy walks give views from above.'),
  ('Sinharaja Forest Reserve','sinharaja-forest-reserve','Forest','Sri Lanka','Sabaragamuwa','Deniyaya',6.4,80.4,'January to April','Morning','A rainforest reserve and UNESCO World Heritage Site with many endemic birds and plants. Leeches are common, so wear proper clothing and walk with a guide.'),
  ('Korup National Park','korup-national-park','Forest','Cameroon','Southwest','Mundemba',5.05,8.85,'December to February','Morning','One of Africa''s oldest and most biodiverse rainforests, with rare primates and thousands of plant species. Trekking is basic and needs a local guide and planning.'),
  ('Redwood National Park','redwood-national-park','Forest','United States','California','Crescent City',41.2132,-124.0046,'May to September','Morning','Home to the tallest trees on Earth, towering coast redwoods in misty forest by the Pacific. Quiet groves such as Lady Bird Johnson Grove have easy paths.'),
  ('Tsitsikamma Forest','tsitsikamma-forest','Forest','South Africa','Eastern Cape','Storms River',-33.9667,23.9,'October to April','Morning','Ancient forest meeting the Indian Ocean, with swing bridges over the Storms River mouth. The Otter Trail is a famous multi-day coastal hike.'),
  ('Danum Valley','danum-valley','Forest','Malaysia','Sabah','Lahad Datu',4.9667,117.8,'March to October','Morning','A protected lowland rainforest in Borneo with orangutans, pygmy elephants and giant trees. Canopy walkways and guided night walks show its wildlife.'),
  ('Yakushima','yakushima','Forest','Japan','Kagoshima','Yakushima',30.3333,130.5,'April to June','Morning','A mossy island forest of ancient cedars, some over a thousand years old, said to have inspired film forests. It is one of Japan''s wettest places.'),
  ('Taman Negara','taman-negara','Forest','Malaysia','Pahang','Kuala Tahan',4.35,102.4,'March to October','Morning','One of the world''s oldest rainforests, with jungle trekking, river boats and a canopy walkway. Overnight wildlife hides give a chance to see animals.'),
  ('Sequoia National Park','sequoia-national-park','Forest','United States','California','Three Rivers',36.4864,-118.5658,'May to September','Morning','Groves of giant sequoias, the largest trees on Earth by volume, including the General Sherman Tree. The Giant Forest has easy trails among the trunks.'),
  ('Machu Picchu','machu-picchu','Culture','Peru','Cusco','Aguas Calientes',-13.1631,-72.545,'May to September','Early morning or late afternoon','A 15th-century Inca citadel high in the Andes, with terraces, temples and stonework fitted without mortar. Entry uses timed tickets, so book ahead.'),
  ('Angkor Wat','angkor-wat','Culture','Cambodia','Siem Reap','Siem Reap',13.4125,103.867,'November to February','Early morning or late afternoon','The largest religious monument in the world, a 12th-century Khmer temple in a vast ancient complex. Sunrise over its towers is the classic view.'),
  ('Petra','petra','Culture','Jordan','Ma''an','Wadi Musa',30.3285,35.4444,'March to May and September to November','Early morning or late afternoon','A city carved into rose-coloured rock by the Nabataeans, reached through a narrow canyon. The Treasury is the famous facade, and a full day is worth allowing.'),
  ('Colosseum','colosseum','Culture','Italy','Lazio','Rome',41.8902,12.4922,'April to June and September to October','Early morning or late afternoon','Rome''s great Roman amphitheatre, built nearly 2,000 years ago to host public spectacles. Timed tickets cut queues, and early morning is quieter.'),
  ('Taj Mahal','taj-mahal','Culture','India','Uttar Pradesh','Agra',27.1751,78.0421,'October to March','Early morning or late afternoon','A white marble mausoleum built in the 17th century beside the Yamuna River. It looks different at sunrise, and it is closed to visitors on Fridays.'),
  ('Great Wall at Mutianyu','great-wall-at-mutianyu','Culture','China','Beijing','Huairou',40.4319,116.5704,'April to October','Early morning or late afternoon','A well-restored section of the Great Wall with watchtowers along forested ridges north of Beijing. A cable car and toboggan run are available.'),
  ('Oia','oia','Culture','Greece','South Aegean','Santorini',36.4618,25.3753,'April to October','Early morning or late afternoon','A clifftop village of white houses and blue-domed churches above the Aegean caldera. It is famous for its sunsets and gets very crowded in the evening.'),
  ('Chichen Itza','chichen-itza','Culture','Mexico','Yucatan','Tinum',20.6843,-88.5678,'November to March','Early morning or late afternoon','A major Maya city with the stepped El Castillo pyramid at its heart. Arrive at opening time to beat the heat and the crowds.'),
  ('Alhambra','alhambra','Culture','Spain','Andalusia','Granada',37.176,-3.5881,'March to May and September to October','Early morning or late afternoon','A hilltop palace and fortress of the Nasrid dynasty, famous for carved plaster and tilework. Tickets sell out, so book well ahead.'),
  ('Hagia Sophia','hagia-sophia','Culture','Turkey','Istanbul','Istanbul',41.0086,28.9802,'April to May and September to November','Early morning or late afternoon','A 6th-century building with a vast dome in Istanbul''s old city, once a cathedral and now a mosque. Dress modestly and expect busy queues.'),
  ('Fes el-Bali','fes-el-bali','Culture','Morocco','Fes-Meknes','Fes',34.0645,-4.973,'March to May and September to November','Early morning or late afternoon','The old walled medina of Fes, a maze of lanes, tanneries and medieval madrasas. Hire a licensed guide the first time to find your way.'),
  ('Great Zimbabwe','great-zimbabwe','Culture','Zimbabwe','Masvingo','Masvingo',-20.267,30.933,'May to October','Early morning or late afternoon','The stone ruins of a medieval city that gave Zimbabwe its name, with a hilltop complex and the Great Enclosure. It was the centre of a powerful trading kingdom.'),
  ('Foumban Royal Palace','foumban-royal-palace','Culture','Cameroon','West','Foumban',5.727,10.898,'November to March','Early morning or late afternoon','The palace of the Bamoun kings, built in the early 1900s, with a museum of royal art and history. Foumban is known for craftsmen working in bronze and wood.'),
  ('Fushimi Inari Shrine','fushimi-inari-shrine','Culture','Japan','Kyoto','Kyoto',34.9671,135.7727,'March to May and October to November','Early morning or late afternoon','A shrine famous for thousands of vermilion torii gates winding up a forested hill. It is open all day, and early or late visits are far quieter.'),
  ('Pyramids of Giza','pyramids-of-giza','Culture','Egypt','Giza','Giza',29.9792,31.1342,'October to April','Early morning or late afternoon','The last surviving wonder of the ancient world, built over 4,500 years ago as royal tombs beside the Sphinx. Start early to avoid the midday heat.')
  ) as v(name, slug, category, country, region, city, latitude, longitude, best_season, best_time, description)
  -- Skip anything you already added yourself, even if you named or spelled it a little differently.
  where not exists (
          select 1 from public.places p
          where p.slug = v.slug or p.slug like v.slug || '-%'
             or regexp_replace(lower(p.name), '[^a-z0-9]+', '', 'g') = regexp_replace(lower(v.name), '[^a-z0-9]+', '', 'g'))
    and not exists (
          select 1 from (values
            ('victoria-falls', '%victoria%'),
            ('lake-malawi', '%malawi%'),
            ('mount-cameroon', '%cameroon%'),
            ('anse-source-d-argent', '%source%argent%'),
            ('bwindi-impenetrable-forest', '%bwindi%')
          ) as skip(slug, pattern)
          join public.places p on p.name ilike skip.pattern
          where skip.slug = v.slug)
  on conflict (slug) do nothing;
end $$;
