-- seed-places.sql: up to 95 starter places, each with a full description, country, how to get there,
-- entry fee, best season and best time. Places you already added yourself are skipped.
-- Run ONCE in the Supabase SQL editor AFTER schema.sql, after you have signed in with your admin Google account
-- and added yourself to public.admins. Safe to re-run:
--   * missing places are added as DRAFT (no photo yet); in /admin.html tap "Add photos to new places" to give each a
--     real Unsplash photo and publish it;
--   * places from the earlier, shorter seed are upgraded to the full information below, but only if you have not
--     edited them (their placeholder access and fee text are still unchanged).
-- Fees and times are approximate and change often, so each fee says to confirm before you go.
do $$
declare owner uuid;
begin
  select u.id into owner from auth.users u join public.admins a on a.email = lower(u.email) order by a.email limit 1;
  if owner is null then
    raise exception 'Sign in to TerraLens with your admin Google account first, and add that email to public.admins.';
  end if;
  insert into public.profiles (id) values (owner) on conflict (id) do nothing;

  create temporary table seed_places on commit drop as
  select * from (values
  ('Victoria Falls','victoria-falls','Waterfall','Zimbabwe','Matabeleland North','Victoria Falls',-17.9243,25.8572,'February to May for the biggest flow; September to December for clearer views','Morning for fewer crowds and rainbows; full-moon evenings for a ''moonbow'' on selected tours','Fly to Victoria Falls Airport or cross from Livingstone in Zambia (about 10 km). The park entrance is in Victoria Falls town and the main viewpoints are a short, signed walk along the cliff.','About US$50 for foreign adults on the Zimbabwe side; the Zambian side is cheaper (approximate; confirm before you go)','A curtain of water nearly 1.7 km wide where the Zambezi River drops into a narrow gorge on the Zimbabwe-Zambia border. The spray rises high enough to be seen from far away. Viewpoints face the Main Falls, the Devil''s Cataract and the Eastern Cataract, and the Knife-Edge Bridge gives spray-soaked views. Bring a raincoat in high water, and expect the spray to hide the falls near peak flow.'),
  ('Iguazu Falls','iguazu-falls','Waterfall','Argentina','Misiones','Puerto Iguazu',-25.6953,-54.4367,'March to May and August to November','Early morning when the park opens, or late afternoon; weekdays are quieter','Fly to Puerto Iguazu (IGR) in Argentina or Foz do Iguacu (IGU) in Brazil. The Argentine park is about 20 minutes from Puerto Iguazu by bus or taxi; the Brazilian side has its own entrance.','About US$30-45 for foreign adults on the Argentine side and about US$30-35 on the Brazilian side (approximate; confirm before you go)','A vast system of about 270 waterfalls across the Argentina-Brazil border, set in subtropical rainforest. The Devil''s Throat is the most powerful drop. On the Argentine side, upper and lower circuits and a small train lead to the Devil''s Throat walkway. The Brazilian side adds wide panoramic views, and the two sides are best seen on separate days.'),
  ('Niagara Falls','niagara-falls','Waterfall','Canada','Ontario','Niagara Falls',43.0962,-79.0377,'May to October','Early morning for fewer people, or after dark when the falls are lit up','Fly into Buffalo (BUF) or Toronto (YYZ, about 90 minutes by road). The falls are walkable from the town of Niagara Falls, Ontario, and trains and buses link it with Toronto in summer.','Viewing from the promenade is free; boat tours, Journey Behind the Falls and observation decks cost roughly CAD 25-70 each, and parking is paid (approximate; confirm before you go)','Three famous waterfalls on the Niagara River at the border of Canada and the United States. Boat tours and walkways take visitors right up to the spray. Boats carry visitors close to the base of the Horseshoe Falls, and tunnels let you stand behind the curtain of water. Fireworks and illumination happen on summer evenings.'),
  ('Angel Falls','angel-falls','Waterfall','Venezuela','Bolivar','Canaima National Park',5.9701,-62.5362,'June to December, when rain gives fuller flow','Morning, when the top is least likely to be hidden in cloud','Fly from Caracas or Ciudad Bolivar to Canaima, then take a motorised canoe upriver (about 4-5 hours, in the rainy season only) and a short jungle hike to the viewpoint. Trips are normally arranged with a licensed operator; check current travel advice for Venezuela.','Park fees plus a guided tour, which usually costs several hundred US dollars','The world''s tallest uninterrupted waterfall, falling from a flat-topped tepui in Canaima National Park. It is reached by river and a jungle trek. At 979 metres, with an uninterrupted drop of about 807 metres, it falls from the flat top of Auyan-tepui. Much of the water turns to mist before it reaches the ground.'),
  ('Kaieteur Falls','kaieteur-falls','Waterfall','Guyana','Potaro-Siparuni','Kaieteur National Park',5.1753,-59.4813,'May to August and November to January','Midday flights; morning light for photos','Charter day flights from Georgetown land at the Kaieteur airstrip, and a short forest walk leads to the viewpoints. Overland trips take several days.','The flight tour (about US$250-300 per person) is the main cost; the park fee is small (approximate; confirm before you go)','One of the world''s largest single-drop waterfalls by volume, on the Potaro River. It is usually reached by a short flight from Georgetown. Roughly 226 metres high, it is one of the world''s most powerful single-drop falls. Look for the tiny golden frog living in tank bromeliads and for Guianan cock-of-the-rock birds.'),
  ('Gullfoss','gullfoss','Waterfall','Iceland','Southern','Haukadalur',64.3271,-20.1199,'June to August for long days; winter for ice and snow','Early morning or evening in summer; winter days are short but icy and quiet','About 1.5 hours (125 km) by road from Reykjavik on the Golden Circle. A car park and short paved paths lead to two viewpoints, and many bus tours stop here.','Free to visit','A two-tier waterfall on the Hvita River that plunges into a rugged canyon. It is a main stop on Iceland''s Golden Circle route. The river drops about 32 metres in two stages into a deep canyon, and in winter ice shapes the edges. Paths can be slippery and drenched with spray, so wear grippy shoes.'),
  ('Seljalandsfoss','seljalandsfoss','Waterfall','Iceland','Southern','Hvolsvollur',63.6156,-19.9886,'May to September','Evening light in summer, when the sun shines on the falls from the west','About 1.5-2 hours (120 km) from Reykjavik on Route 1, with a car park beside the falls. The path behind the waterfall is open when it is not icy.','No entry fee; parking is paid (roughly ISK 1,000) (approximate; confirm before you go)','A slender waterfall that drops over an old sea cliff, with a path that lets you walk behind the falling water. Evening light is a favourite for photographers. Walk behind the 60-metre curtain of water and bring waterproofs. The hidden waterfall Gljufrabui is a short walk to the north.'),
  ('Skogafoss','skogafoss','Waterfall','Iceland','Southern','Skogar',63.5321,-19.5114,'May to September','Midday sun for rainbows; early or late in the day for fewer people','About 2 hours (150 km) from Reykjavik on Route 1, with a car park near the base. Stairs lead to a viewing platform at the top, and the Fimmvorduhals trail continues beyond it.','No entry fee; parking is paid (roughly ISK 1,000) (approximate; confirm before you go)','A powerful waterfall about 60 metres high and 25 metres wide on Iceland''s south coast, often with a rainbow in the spray. Stairs lead to a viewing platform at the top. The falls are about 60 metres high and 25 metres wide, and a rainbow often forms in sunny weather. You can walk right up to the base, but the spray soaks everything.'),
  ('Krka Waterfalls','krka-waterfalls','Waterfall','Croatia','Sibenik-Knin','Skradin',43.8039,15.9708,'April to June and September','Early morning or late afternoon to avoid tour groups','Entrances at Skradin, Lozovac and Roski Slap are 20-30 minutes from Sibenik by car or bus. Boats run from Skradin, and tickets should be booked online in summer.','Roughly EUR 15 in low season to EUR 40 in July and August (approximate; confirm before you go)','A series of cascades and travertine barriers in Krka National Park, crossed by wooden walkways. Swimming rules change, so check the park''s current guidance. Skradinski Buk has the longest wooden walkway among travertine pools and cascades. Boat trips visit Visovac island and its small monastery; check the current rules on swimming.'),
  ('Ban Gioc-Detian Falls','ban-gioc-detian-falls','Waterfall','Vietnam','Cao Bang','Trung Khanh',22.8556,106.7194,'September to October','Morning mist; September and October for full flow and golden rice fields','About 350 km north of Hanoi. Take a bus to Cao Bang, then about 85 km by road to Trung Khanh and the falls. Bamboo rafts take visitors close to the cascade. Carry your passport near this border area.','A small entrance fee (roughly US$2-3) plus a raft fee (approximate; confirm before you go)','A broad, stepped waterfall on the Quay Son River that forms part of the border between Vietnam and China. Rice fields and limestone hills surround it. The falls spread over several tiers across the border river, with limestone peaks and rice fields behind. Check the viewing rules, as the Chinese side is across the water.'),
  ('Kuang Si Falls','kuang-si-falls','Waterfall','Laos','Luang Prabang','Luang Prabang',19.7525,101.9878,'November to April','Morning, before tour groups arrive around midday','About 30 km (45 minutes) south of Luang Prabang by tuk-tuk, minivan or motorbike. A short paved path leads from the entrance to the pools.','Roughly US$3 for entry (approximate; confirm before you go)','A tiered waterfall with turquoise pools near Luang Prabang, ending in a tall cascade. Forest trails lead to the top, and a bear rescue centre sits near the entrance. Turquoise pools step down below a tall main fall, and some are open for swimming (check the signs). A rescue centre for Asiatic black bears sits near the entrance.'),
  ('Jog Falls','jog-falls','Waterfall','India','Karnataka','Shimoga',14.2294,74.8125,'July to September (monsoon)','Early morning, shortly after the monsoon rains','About 380 km from Bengaluru. Take a bus to Sagara and then to Jog, or a train to Talguppa. The viewpoints are close to the car park.','Small entry and parking fees only (a few dozen rupees)','One of India''s highest plunge waterfalls, where the Sharavathi River drops in several streams. It is at its most dramatic after heavy monsoon rain. Four cascades named Raja, Rani, Roarer and Rocket make up the falls. Flow is controlled by a dam upstream, so water can be low outside the monsoon.'),
  ('Yosemite Falls','yosemite-falls','Waterfall','United States','California','Yosemite National Park',37.7569,-119.5963,'April to June','Late April to June at peak flow; clear spring nights can show a moonbow','In Yosemite Valley, about 4 hours'' drive from San Francisco. A short paved path leads from the shuttle stop to the Lower Fall viewpoint. Reservations may be required in busy periods.','About US$35 per vehicle for the national park (valid for 7 days) (approximate; confirm before you go)','North America''s tallest waterfall, falling in three sections from the rim of Yosemite Valley. Flow is strongest in spring and can dry up by late summer. The Upper Yosemite Fall trail is a strenuous climb of roughly 11 km round trip. The falls can be reduced to a trickle or dry by late summer.'),
  ('Ouzoud Falls','ouzoud-falls','Waterfall','Morocco','Beni Mellal-Khenifra','Azilal',32.0147,-6.7195,'March to June','Morning, when the light creates rainbows over the falls','About 150 km (2.5 hours) from Marrakech by road. A short walk from the village car park leads to viewpoints and a stepped path to the base.','Free entry; small parking tips and optional boat rides cost a few dollars','Tiered waterfalls about 110 metres high in the Middle Atlas mountains, with olive groves and wild macaques along the paths. Boat rides run at the base. Barbary macaques live along the paths, and restaurants line the top and the base. The surrounding olive groves and red earth make it a good day trip.'),
  ('Lobe Falls','lobe-falls','Waterfall','Cameroon','South','Kribi',2.88,9.9,'December to February (dry season)','Morning at low tide; December to February for calm seas','About 8 km south of Kribi; take a taxi or moto-taxi from town. Local guides run pirogues across the river mouth to the viewpoint.','A small local fee for the pirogue crossing (a few thousand CFA francs)','A rare waterfall that tumbles over rocks straight into the Atlantic Ocean near Kribi. Local guides take visitors by pirogue to see the falls from the water. The Lobe River drops about 20 metres over rocks, partly straight into the Atlantic. A fishing community lives nearby, and fresh grilled fish is easy to find.'),
  ('Tugela Falls','tugela-falls','Waterfall','South Africa','KwaZulu-Natal','Royal Natal National Park',-28.7525,28.8992,'December to March, after summer rain','Start early; December to March for the strongest flow','Drive about 5 hours from Johannesburg to Royal Natal National Park. The hike to the top starts at the Sentinel car park (a rough road; high clearance helps) and is about 13 km round trip.','Conservation fees apply in the park (check the Ezemvelo KZN Wildlife website)','One of the tallest waterfalls in the world, tumbling in five drops from the Drakensberg escarpment. A hike from the Sentinel car park leads to the top. It falls in five drops from the Drakensberg escarpment and is among the tallest waterfalls in the world. In winter it can freeze or run very thin.'),
  ('Mount Kilimanjaro','mount-kilimanjaro','Mountain','Tanzania','Kilimanjaro','Moshi',-3.0674,37.3556,'January to March and June to October','Summit pushes start around midnight to reach the top at sunrise','Fly to Kilimanjaro International Airport (JRO). Routes such as Machame, Lemosho and Marangu start at park gates, and climbing needs a licensed guide and operator.','Park fees are the main cost (roughly US$70-80 per day); full trips usually cost US$2,000-4,000 (approximate; confirm before you go)','Africa''s highest peak, a freestanding volcano rising to 5,895 metres. Several routes lead to the summit, which walkers can reach without technical climbing. Climbs take 5 to 9 days. Altitude sickness is the main risk, so a longer route with more acclimatisation gives a better chance of reaching the summit.'),
  ('Mount Fuji','mount-fuji','Mountain','Japan','Yamanashi and Shizuoka','Fujinomiya',35.3606,138.7274,'Early July to early September for climbing','Start in the afternoon and climb overnight to reach the summit at sunrise','Trains and buses from Tokyo reach Kawaguchiko in about 2 hours, with buses on to the Fifth Stations. The Yoshida Trail is the most popular, and reservations and a climbing fee are required in season.','A climbing fee of about JPY 4,000 on the Yoshida Trail in season (approximate; confirm before you go)','Japan''s highest mountain at 3,776 metres, a near-perfect volcanic cone that is sacred in Japanese culture. The official climbing season is short. Mountain huts cost extra and need booking, and the weather changes quickly, so bring warm and waterproof layers. Outside the official season, climbing is not recommended.'),
  ('Matterhorn','matterhorn','Mountain','Switzerland','Valais','Zermatt',45.9763,7.6586,'June to September for hiking; December to March for skiing','Sunrise, when the east face glows pink','Take the train from Visp to car-free Zermatt (about 3.5 hours from Zurich). The Gornergrat railway and cable cars lead to viewpoints.','Free to view; the Gornergrat railway costs roughly CHF 70-100 return (approximate; confirm before you go)','A pyramid-shaped peak on the Swiss-Italian border and one of the most recognisable mountains in the Alps. Zermatt is the main base for visitors. Hiking trails such as the Five Lakes Walk give mirror-like reflections of the peak. Climbing the Matterhorn itself needs a certified mountain guide.'),
  ('Everest Base Camp','everest-base-camp','Mountain','Nepal','Solukhumbu','Lukla',28.0026,86.8528,'April to May and October to November','Morning, for the clearest views before clouds roll in','Fly from Kathmandu to Lukla (about 30 minutes), then trek for about 8-10 days up and down via Namche Bazaar. Park and local permits are required.','Permits cost roughly US$40-50; guided treks cost more (approximate; confirm before you go)','A famous high-altitude trek through Sherpa villages to the foot of the world''s highest mountain. Altitude sickness is a real risk, so allow time to acclimatise. The trail passes Sherpa villages, monasteries and suspension bridges. Altitude sickness is a real risk, so allow rest days and descend if symptoms get worse.'),
  ('Denali','denali','Mountain','United States','Alaska','Denali National Park',63.0692,-151.007,'June to August','Clear mornings; long daylight from June to August','Drive 385 km (about 5 hours) from Anchorage or take the Alaska Railroad. Private cars can only drive the first 15 miles of the park road, so use the park buses beyond.','Park entrance about US$15 per person; bus fares vary (approximate; confirm before you go)','North America''s highest peak at 6,190 metres, rising above wild tundra in Denali National Park. The park road offers wildlife and mountain views. North America''s tallest peak is often hidden in cloud, so allow several days. Grizzly bears, caribou and Dall sheep are commonly seen from the buses.'),
  ('Torres del Paine','torres-del-paine','Mountain','Chile','Magallanes','Puerto Natales',-50.9423,-73.4068,'November to March','Sunrise at Mirador Las Torres, when the granite towers glow red','Fly to Punta Arenas, take a bus to Puerto Natales (about 3 hours) and then another to the park (about 2 hours). Book campsites and refugios well in advance for the W trek.','Park entry roughly US$30-45 for foreign visitors (approximate; confirm before you go)','Granite towers, glaciers and turquoise lakes in Patagonia. The W and O circuit treks are among South America''s most famous hikes, in very changeable weather. The W trek takes 4-5 days and the full O circuit about 8-10. Patagonian weather can bring wind, rain and sun within an hour.'),
  ('Mount Cameroon','mount-cameroon','Mountain','Cameroon','Southwest','Buea',4.2033,9.1706,'November to April (dry season)','Start early; the dry season from November to April gives the clearest views','Buea is about 1 hour by road from Douala. Climbs begin at the Mount Cameroon ecotourism office in Buea, which arranges guides and porters for 2-3 day trips.','Guide, porter and park fees vary by route and group size','The highest peak in West and Central Africa at about 4,040 metres, an active volcano rising from the Atlantic coast. The annual Race of Hope climbs it from Buea. The mountain is an active volcano, with forest at the base and bare lava near the top. The annual Race of Hope takes runners up and down in a single day.'),
  ('Table Mountain','table-mountain','Mountain','South Africa','Western Cape','Cape Town',-33.9628,18.4098,'October to March','Early morning, or late afternoon for sunset; avoid windy days when the cable car closes','Drive or take a taxi to the Lower Cableway Station (about 10 minutes from the centre of Cape Town), or hike from Kloof Nek, Platteklip Gorge or other trails.','Return cable car roughly ZAR 400-500 for adults; hiking is free (approximate; confirm before you go)','A flat-topped mountain overlooking Cape Town and the Atlantic. Visitors hike one of several trails or ride the cable car, which closes in strong wind. Platteklip Gorge is the most direct hike, about 1.5-2.5 hours up. Clouds often pour over the top like a ''tablecloth'', and weather can change quickly.'),
  ('Tre Cime di Lavaredo','tre-cime-di-lavaredo','Mountain','Italy','South Tyrol and Veneto','Auronzo',46.619,12.302,'June to September','Early morning for soft light and thinner crowds','Drive to Rifugio Auronzo via a toll road from Misurina; in summer buses run from Dobbiaco and Misurina. The loop trail around the peaks is about 10 km.','The toll road costs roughly EUR 30 per car (approximate; confirm before you go)','Three dramatic limestone peaks in the Dolomites, ringed by an easy and popular loop trail. Mountain huts along the route serve meals with the peaks in view. The loop passes mountain huts where you can eat with the peaks in view. Weather and snow can close the high trails outside summer.'),
  ('Mount Rainier','mount-rainier','Mountain','United States','Washington','Mount Rainier National Park',46.8523,-121.7603,'July to September','Mornings, when the mountain is most often clear; late July to August for wildflowers','Drive about 2 hours from Seattle to Paradise or Sunrise. Some roads are seasonal, and timed-entry reservations may apply in summer.','About US$30 per vehicle (valid for 7 days) (approximate; confirm before you go)','A glaciated volcano of 4,392 metres south-east of Seattle, surrounded by wildflower meadows in summer. Paradise and Sunrise are the main viewpoints. Meadows around Paradise bloom with wildflowers in summer, and Skyline Trail gives glacier views. Climbing the summit needs training, a permit and glacier gear.'),
  ('Mount Kenya','mount-kenya','Mountain','Kenya','Central','Nanyuki',-0.1521,37.3084,'January to February and August to September','Summit attempts start before dawn to see sunrise from Point Lenana','From Nairobi, drive about 3 hours to the Naro Moru, Sirimon or Chogoria gates. Guides and porters are required.','Park fees of roughly US$90 per day for foreign adults, plus guide and porter costs (approximate; confirm before you go)','Africa''s second-highest mountain, with jagged glaciated peaks right on the equator. Trekkers cross moorland, forest and alpine zones to reach Point Lenana. The trail crosses moorland, bamboo forest and alpine zones with giant groundsel plants. Point Lenana is a trekkers'' summit, while Batian and Nelion need technical climbing.'),
  ('Annapurna Circuit','annapurna-circuit','Mountain','Nepal','Gandaki','Pokhara',28.5961,83.8203,'March to May and October to November','Early starts for Thorong La; clear mornings and cloudy afternoons','Take a bus from Kathmandu or Pokhara to Besisahar (6-8 hours). Roads now cover much of the route, so many trekkers use jeeps for some sections and walk the upper parts.','Annapurna Conservation Area permit and TIMS card cost roughly US$30-50 together (approximate; confirm before you go)','A classic Himalayan trek that crosses the high Thorong La pass and passes through varied valleys and villages. It can also be hiked in sections. The route crosses the 5,416-metre Thorong La pass and passes through varied valleys and villages. It can also be hiked in sections.'),
  ('Mount Bromo','mount-bromo','Mountain','Indonesia','East Java','Probolinggo',-7.9425,112.953,'April to October','Sunrise, at about 4 to 5 am','Fly to Surabaya or Malang, then drive 3-4 hours to Cemoro Lawang. Jeeps take visitors to the Penanjakan viewpoint before sunrise and across the sea of sand.','National park ticket roughly IDR 220,000-320,000 for foreigners (about US$15-20), plus jeep hire (approximate; confirm before you go)','An active volcano in a vast sandy caldera, best visited at sunrise from the Penanjakan viewpoint. Expect fine volcanic dust and cold early mornings. Fine volcanic dust and cold early mornings are normal, so bring a mask and warm clothes. You can walk or ride a horse to the crater rim.'),
  ('Huangshan','huangshan','Mountain','China','Anhui','Huangshan City',30.133,118.17,'April to May and September to November','Sunrise and sunset for the ''sea of clouds''; avoid Chinese holiday weeks','Take the high-speed train to Huangshan North station, then a bus to the park gates (30-60 minutes). Cable cars and long stone staircases reach the peaks.','About CNY 190 in high season, plus cable cars of roughly CNY 80-90 each (approximate; confirm before you go)','The Yellow Mountains are known for granite peaks, twisted pines and seas of cloud. Stone staircases and cable cars make the summits reachable. Granite peaks and twisted pines rise from the mist, and staying overnight on the mountain gives sunrise views. Stairs are steep and busy in holiday periods.'),
  ('Mount Toubkal','mount-toubkal','Mountain','Morocco','Marrakech-Safi','Imlil',31.059,-7.9161,'April to June and September to October','Start early and summit before the midday winds','Drive 1.5 hours from Marrakech to Imlil. Local guides and mules are available, and most climbers take two days, sleeping at the Toubkal refuge.','No park fee; guides cost roughly MAD 600-800 per day and a refuge bed about MAD 150-250 (approximate; confirm before you go)','The highest peak in North Africa at 4,167 metres, reached from the Berber village of Imlil in the High Atlas. It is a demanding but non-technical hike in summer. At 4,167 metres it is the highest peak in North Africa. In summer it is a demanding but non-technical hike, and winter needs snow gear.'),
  ('Fitz Roy','fitz-roy','Mountain','Argentina','Santa Cruz','El Chalten',-49.2711,-72.9553,'December to March','Sunrise at Laguna de los Tres, when the granite glows red','Take a bus from El Calafate to El Chalten (about 3 hours). Trails start from the village, and Laguna de los Tres is about 20 km round trip.','Trails from El Chalten are currently free; check local rules','A sharp granite spire that dominates the skyline of El Chalten in Patagonia. Day hikes lead to Laguna de los Tres, with views of the peak at sunrise. The jagged granite spire towers over El Chalten, and views depend on the weather. Other day hikes lead to Laguna Torre and Cerro Torre viewpoints.'),
  ('Grace Bay','grace-bay','Beach','Turks and Caicos','Providenciales','Grace Bay',21.794,-72.18,'December to April','Morning for calm water; sunset walks','Fly to Providenciales (PLS), then about 20 minutes by taxi to the beachfront resorts. The beach itself is public.','Free; resort and watersports prices vary','A long stretch of soft white sand and shallow turquoise water protected by a barrier reef. Calm conditions make it good for swimming and snorkelling. Shallow, calm water behind a barrier reef makes it ideal for swimming and paddleboarding. Smith''s Reef nearby is a good snorkelling spot.'),
  ('Anse Source d''Argent','anse-source-d-argent','Beach','Seychelles','La Digue','La Digue',-4.3721,55.828,'April to May and October to November','Low tide in the early morning or late afternoon for soft, pink-gold light','Take the ferry from Praslin to La Digue (about 15 minutes), then rent a bicycle and ride about 3 km to L''Union Estate, the access point.','L''Union Estate entry about SCR 100-150 (approximate; confirm before you go)','A famous beach framed by smooth granite boulders and shallow lagoons. Visit at low tide and in the morning for the best light and calm water. Smooth granite boulders and shallow lagoons make it one of the most photographed beaches in the world. Swimming can be limited by rocks and seaweed, so check conditions.'),
  ('Whitehaven Beach','whitehaven-beach','Beach','Australia','Queensland','Whitsunday Island',-20.2827,149.0383,'September to November','Low tide for the best swirls at Hill Inlet; mornings for fewer boats','Reach it by boat or seaplane from Airlie Beach, Hamilton Island or Shute Harbour. Many day trips include the Hill Inlet lookout.','The beach is free; boat or seaplane trips cost roughly AUD 100-250 per person (approximate; confirm before you go)','Seven kilometres of pure white silica sand on Whitsunday Island. The swirling sand and water patterns at Hill Inlet are best seen from the lookout. Seven kilometres of fine white silica sand stay cool underfoot. In stinger season (roughly November to May) wear a protective suit when swimming.'),
  ('Navagio Beach','navagio-beach','Beach','Greece','Ionian Islands','Zakynthos',37.8597,20.6247,'May to September','Around midday when the sun reaches the cove, which is in morning shade','Boat trips leave from Porto Vromi, Zakynthos Town and Agios Sostis. A cliff-top viewing platform is reachable by car.','The viewpoint is free; boat trips cost roughly EUR 20-50 per person (approximate; confirm before you go)','A secluded cove with white sand and tall cliffs, known for a shipwreck on the shore. It is reached by boat, and the cliff viewpoint above gives the classic photo. The beach is known for a shipwreck on its sand and can only be reached by sea. Rockfall risk means some days landing is not allowed, so check locally.'),
  ('Praia das Catedrais','praia-das-catedrais','Beach','Spain','Galicia','Ribadeo',43.5527,-7.1561,'June to September, at low tide','At low tide (check tide tables); sunrise or late afternoon for photos','Drive or take a bus to Ribadeo on the Galician coast. In high season a free online reservation is required to visit at low tide.','Free, but online booking of a free pass is required in busy periods','A beach lined with towering rock arches carved by the sea. It can only be explored safely at low tide, so check tide times and book ahead in summer. The sea has carved rock arches up to 30 metres high. Tides come in fast, so leave the beach well before the water returns.'),
  ('Bondi Beach','bondi-beach','Beach','Australia','New South Wales','Sydney',-33.8908,151.2743,'November to March','Early morning for swimmers and surf lessons; the Bondi to Coogee coastal walk at sunrise','Take a train to Bondi Junction and then bus 333 (about 15 minutes). From the city centre it takes about 30 minutes.','Free','Sydney''s best-known beach, with surf, an ocean pool and a coastal walk to Coogee. Lifeguards patrol the flagged areas, so swim between the flags. Swim between the red and yellow flags where lifeguards patrol. The Icebergs ocean pool and cafes line the south end.'),
  ('Railay Beach','railay-beach','Beach','Thailand','Krabi','Railay',8.0116,98.8372,'November to April','Low tide for walking between beaches; late afternoon for climbers'' golden light','Take a longtail boat from Ao Nang (about 10 minutes) or Krabi Town. There is no road access to the peninsula.','Free; the boat fare is roughly THB 100-200 (approximate; confirm before you go)','A beach on a peninsula reachable only by boat, framed by limestone cliffs popular with rock climbers. Phra Nang Beach nearby has a cave shrine. Limestone cliffs on three sides give the peninsula its famous rock climbing. Phra Nang Beach has a cave shrine, and a viewpoint trail leads to a hidden lagoon.'),
  ('Matira Beach','matira-beach','Beach','French Polynesia','Society Islands','Bora Bora',-16.53,-151.745,'May to October','Morning for the clearest lagoon colours','Fly to Bora Bora, take a boat to the main island at Vaitape and then a taxi or bicycle about 5 km to Matira Point. The beach is public.','Free','A long public beach on Bora Bora with calm, clear shallows and views of Mount Otemanu. It is one of the island''s most accessible places to swim. Calm, shallow water and soft white sand make it good for swimming and snorkelling. Mount Otemanu is visible across the lagoon.'),
  ('Kribi Beach','kribi-beach','Beach','Cameroon','South','Kribi',2.9404,9.9102,'December to February','Morning when fishing boats return; December to February for drier weather','About 3 hours (150 km) by road from Douala, with shared taxis and buses. Beaches begin at the town and run south along the coast.','Free; beach-bar and activity prices vary','Palm-fringed sand on the Atlantic coast of Cameroon, known for fresh seafood and a relaxed atmosphere. Fishing pirogues work from the shore in the morning. Palm-fringed sand meets the Atlantic, and fresh grilled fish is sold along the shore. Pygmy villages and the Lobe Falls are nearby.'),
  ('Limbe Down Beach','limbe-down-beach','Beach','Cameroon','Southwest','Limbe',4.0186,9.2062,'December to February','Late afternoon when fishermen bring in their catch','Limbe is about 1.5-2 hours by road from Douala and about 30-45 minutes from Buea, with shared taxis from both.','Free','A black volcanic sand beach in Limbe with Mount Cameroon rising behind it. Fishermen land their catch here and grilled fish is sold nearby. The dark volcanic sand comes from Mount Cameroon, which rises behind the town. Nearby are the botanic garden and wildlife centre.'),
  ('Copacabana Beach','copacabana-beach','Beach','Brazil','Rio de Janeiro','Rio de Janeiro',-22.9711,-43.1822,'December to March','Early morning for quiet walks; sunset at Arpoador near the Ipanema end','Take the metro to Cardeal Arcoverde or Siqueira Campos stations, or a taxi or bus from the city centre (30-45 minutes).','Free','Four kilometres of city beach beside a famous black-and-white wave-pattern promenade. Early mornings are quieter and weekends are lively. The famous black-and-white wave promenade runs along four kilometres of beach. Keep valuables out of sight and avoid the beach late at night.'),
  ('Camps Bay','camps-bay','Beach','South Africa','Western Cape','Cape Town',-33.95,18.378,'November to March','Late afternoon to sunset; the Atlantic water is cold even in summer','About 15 minutes by car from the centre of Cape Town via Kloof Nek; MyCiTi buses also go there.','Free; beachfront parking is metered','A wide white-sand beach beneath the Twelve Apostles mountains, with palm trees and cafes behind. The Atlantic water is cold, but the sunsets are superb. The beach lies below the Twelve Apostles mountains with palm trees and cafes behind. Strong afternoon winds can blow sand across the beach.'),
  ('White Beach, Boracay','white-beach-boracay','Beach','Philippines','Western Visayas','Boracay',11.965,121.923,'November to May','Early morning for calm water and clean sand; sunset at Station 1','Fly to Caticlan (MPH) or Kalibo, then take a boat to the island (about 15 minutes from Caticlan). The beach is divided into Stations 1 to 3.','Free; environmental and terminal fees apply on arrival (roughly PHP 100-300) (approximate; confirm before you go)','A four-kilometre white-sand beach with calm water, watersports and lively evenings. Different stretches suit quiet or social tastes. Station 1 is quieter, Station 2 is the busiest, and Station 3 has fewer crowds. Water sports and evening bars line the sand.'),
  ('Diani Beach','diani-beach','Beach','Kenya','Kwale','Diani',-4.31,39.58,'December to March and July to October','Low tide for long walks; morning for snorkelling trips','Fly to Ukunda (UKA) or Mombasa (MBA), then 30-60 minutes by road (the Likoni ferry or the Dongo Kundu bridge). Public access points run along the beach.','Free; some access points go through resorts','A long coral-sand beach on Kenya''s south coast, with palm trees and warm Indian Ocean water. Snorkelling and kite surfing are popular. Warm Indian Ocean water and white coral sand stretch for about 17 km. Colobus monkeys live in the coastal forest behind the beach.'),
  ('Nungwi Beach','nungwi-beach','Beach','Tanzania','Zanzibar','Nungwi',-5.725,39.299,'June to October and December to February','Mornings; sunset from the northern tip; high tide for swimming','Fly to Zanzibar (ZNZ), then drive about 1 hour (60 km) north. You can also take the ferry from Dar es Salaam to Stone Town.','Free','A beach at the northern tip of Zanzibar with clear water and traditional dhow building nearby. Tides change the shoreline a lot, so check them. Tides change the shoreline a lot, so check the tide tables before swimming. Dhow builders still work nearby, and a turtle sanctuary sits at Mnarani.'),
  ('Tulum Beach','tulum-beach','Beach','Mexico','Quintana Roo','Tulum',20.2114,-87.4654,'November to April','Early morning at opening, to avoid heat and crowds','Fly to Cancun and drive about 2 hours south, or use the airport at Tulum. Beach clubs line the coast, and Playa Paraiso is near the ruins.','The beach is public; the archaeological site ticket costs roughly MXN 100 (approximate; confirm before you go)','A white-sand beach below Mayan ruins on the Caribbean coast. Visit early to avoid crowds, and use reef-safe sunscreen. The Mayan ruins sit on a cliff above the sand. Use reef-safe sunscreen and respect rules on protecting sea turtle nests.'),
  ('Lake Louise','lake-louise','Lake','Canada','Alberta','Banff National Park',51.4254,-116.1773,'June to September; winter for skating','Sunrise before the crowds; June to September, or winter for skating','Drive 55 km (about 45 minutes) from Banff. Parking at the lake fills early, so use the Parks Canada shuttle in summer.','A Parks Canada day pass costs about CAD 11 per adult; shuttle fares are extra (approximate; confirm before you go)','A glacier-fed lake of striking turquoise colour in Banff National Park, surrounded by peaks. Trails lead to teahouses and viewpoints above the water. Glacier-fed water gives the lake its unusual turquoise colour. Trails lead to tea houses and viewpoints above the water.'),
  ('Moraine Lake','moraine-lake','Lake','Canada','Alberta','Banff National Park',51.3217,-116.186,'June to September','Sunrise for the best colours','Moraine Lake Road is closed to private cars, so reach it by shuttle or Parks Canada bus from Lake Louise. Book in advance for peak season.','A Parks Canada pass plus shuttle fare (roughly CAD 8-10) (approximate; confirm before you go)','A deep blue lake in the Valley of the Ten Peaks, famous from the Rockpile viewpoint. Access is by shuttle in the main season, so plan ahead. The deep blue lake lies in the Valley of the Ten Peaks, and the Rockpile viewpoint gives the classic view. The area is a bear habitat, so carry bear spray and walk in groups.'),
  ('Lake Como','lake-como','Lake','Italy','Lombardy','Como',46.016,9.257,'April to October','Morning ferries for calm water; spring or early autumn to avoid crowds','Take a train from Milan to Como San Giovanni (about 40 minutes). Ferries link villages such as Bellagio, Varenna and Menaggio.','Free to visit; ferries cost roughly EUR 3-15 per ride (approximate; confirm before you go)','A long, deep Alpine lake with villas, gardens and mountain-backed villages. Ferries link towns such as Bellagio, Varenna and Menaggio. Villas and gardens, including Villa del Balbianello, line the shore. The lake''s three arms form an inverted Y shape.'),
  ('Lake Garda','lake-garda','Lake','Italy','Veneto and Lombardy','Sirmione',45.6,10.67,'April to October','Morning for calm water; afternoon winds suit sailing','Take a train to Desenzano or Peschiera from Milan or Verona, then use lake ferries or buses. Sirmione is on a peninsula reached by road.','Free to visit; Sirmione''s Scaligero Castle costs roughly EUR 8 (approximate; confirm before you go)','Italy''s largest lake, with lemon groves, castles and lively waterfront towns. The north is mountainous and windy, with good sailing and windsurfing. The north is mountainous and windy, with good sailing and windsurfing, and the south has gentle beaches. Gardaland and thermal spas are nearby.'),
  ('Lake Bled','lake-bled','Lake','Slovenia','Upper Carniola','Bled',46.3639,14.0938,'May to September','Sunrise for mist over the water','About 55 km (1 hour) from Ljubljana by bus or car. Walk the 6 km lakeside path or take a traditional pletna boat to Bled Island.','Free to walk the lake; the pletna boat costs roughly EUR 20 per person and the island church roughly EUR 6-10 (approximate; confirm before you go)','A glacial lake with a tiny island church and a clifftop castle. A traditional pletna boat carries visitors to the island. A medieval castle sits on a cliff above the lake. Try the local cream cake, kremsnita, at the lakeside cafes.'),
  ('Plitvice Lakes','plitvice-lakes','Lake','Croatia','Lika-Senj','Plitvica',44.8654,15.582,'April to October','Early morning or late afternoon; autumn for colours','Take a bus from Zagreb (about 2 hours) to Entrance 1 or 2. An electric boat and a panoramic train run inside the park.','Tickets cost roughly EUR 10 in winter to EUR 40 in summer; buy online (approximate; confirm before you go)','Sixteen terraced lakes joined by waterfalls and wooden walkways inside a national park. Colours change with minerals and light, and it is busy in summer. The sixteen lakes are joined by cascades and wooden walkways, and colours change with minerals and light. Swimming is not allowed.'),
  ('Lake Geneva','lake-geneva','Lake','Switzerland','Vaud','Lausanne',46.45,6.53,'May to September','Sunset from Lausanne or Nyon; summer for swimming','Fly to Geneva (GVA) or take a train from Zurich (about 3 hours). CGN steamers cross the lake between towns.','Free to visit; boat tickets from roughly CHF 15 (approximate; confirm before you go)','A crescent-shaped lake shared by Switzerland and France, with vineyards, castles and Alpine views. Lake steamers connect the shoreline towns. Vineyards of Lavaux, the Chillon Castle and the Alps give the shoreline its character. Bains des Paquis in Geneva is a popular swimming spot.'),
  ('Lake Titicaca','lake-titicaca','Lake','Peru','Puno','Puno',-15.8402,-70.0219,'April to October','Morning for calm water and clear light','Fly to Juliaca (JUL) and drive about 1 hour to Puno. Boats leave Puno harbour for the Uros and Taquile islands. Allow time to adjust to the altitude of nearly 3,800 metres.','Boat tours cost roughly PEN 30-80; island entry fees are small (approximate; confirm before you go)','One of the highest large navigable lakes in the world, shared by Peru and Bolivia. Visit the reed islands of the Uros people and Taquile Island. The Uros people live on islands built from totora reeds, and Taquile is known for its weaving. Nights are cold and the sun is strong at this altitude.'),
  ('Lake Kivu','lake-kivu','Lake','Rwanda','Western Province','Rubavu',-1.68,29.25,'June to September','Sunset at Rubavu beaches; morning for boat trips','From Kigali drive about 3 hours (150 km) to Gisenyi (Rubavu) or Kibuye (Karongi). Public buses are available.','Free to visit the shore; boat and kayak trips are priced by the operator','A calm lake in the Rwandan highlands with islands, hot springs and lakeside towns such as Rubavu and Kibuye. Kayaking and boat trips are popular. The lake lies in a rift valley with islands, hot springs and lakeside towns. Swimming is generally considered safe but ask locally before getting in.'),
  ('Crater Lake','crater-lake','Lake','United States','Oregon','Crater Lake National Park',42.9446,-122.109,'July to September','Early morning for calm, mirror-like water; July to September for open roads','Drive from Medford (about 1.5 hours) or Klamath Falls (about 1 hour). Rim Drive is partly closed by snow for much of the year.','About US$30 per vehicle in summer (approximate; confirm before you go)','The deepest lake in the United States, filling the caldera of a collapsed volcano with intensely blue water. Rim Drive circles the lake with many viewpoints. At about 594 metres deep, it is the deepest lake in the United States. Cleetwood Cove trail is the only way down to the water for a boat tour.'),
  ('Lake Tekapo','lake-tekapo','Lake','New Zealand','Canterbury','Tekapo',-44.005,170.476,'October to April','After dark for stargazing; sunrise lights the lake; lupins bloom in November and December','Drive from Christchurch (about 3.5 hours) or take a coach. The Church of the Good Shepherd is a short walk from the village.','Free (donations welcome); Mount John Observatory tours cost roughly NZD 60-150 (approximate; confirm before you go)','A turquoise glacial lake in a dark-sky reserve. The Church of the Good Shepherd sits on the shore, and lupins bloom nearby in late spring. The lake lies in the Aoraki Mackenzie Dark Sky Reserve. Photograph the church and the stars, but respect the no-photography rules inside the church.'),
  ('Lake Atitlan','lake-atitlan','Lake','Guatemala','Solola','Panajachel',14.687,-91.202,'November to April','Mornings, before the afternoon winds known as the Xocomil','Take a shuttle from Guatemala City or Antigua (2.5-3.5 hours) to Panajachel. Public boats (lanchas) run between villages.','Free; boat rides cost roughly GTQ 20-30 per hop (approximate; confirm before you go)','A volcano-ringed lake in the Guatemalan highlands with Mayan villages on its shores. Small boats run between the towns, each with its own character. Three volcanoes rise above the lake, and each village has its own character and markets. Take care of valuables on hikes.'),
  ('Lake Malawi','lake-malawi','Lake','Malawi','Southern Region','Cape Maclear',-14.019,34.834,'May to October','Morning for snorkelling; May to October is the dry season','Fly to Lilongwe, then drive about 4 hours to Monkey Bay and Cape Maclear in Lake Malawi National Park.','Park entry roughly US$10-20 for foreign visitors (approximate; confirm before you go)','A vast freshwater lake, home to hundreds of colourful cichlid fish, with sandy bays and islands. Snorkelling and kayaking are popular at Cape Maclear. Hundreds of colourful cichlid fish live in the clear water. Kayak trips visit rocky islands, and bilharzia risk is local, so seek advice before swimming.'),
  ('Lake Bosumtwi','lake-bosumtwi','Lake','Ghana','Ashanti','Abono',6.5,-1.4167,'November to March','Morning; November to March is dry but hazy from Harmattan dust','About 30 km (45 minutes) from Kumasi by car or taxi to the lakeside village of Abono.','A small local access fee (a few cedis)','A near-circular crater lake formed by a meteorite impact, sacred to the Ashanti people. Forested hills and fishing villages surround the water. This near-circular crater lake formed by a meteorite impact is sacred to the Ashanti people. Fishing is done from wooden boards, and traditional taboos apply on some days.'),
  ('Lake Barombi Mbo','lake-barombi-mbo','Lake','Cameroon','Southwest','Kumba',4.66,9.4,'November to March','Early morning for birds and canoe trips','The lake is near Kumba, about 1.5-2 hours by road from Buea. Take a moto-taxi to the village of Barombi Kotto and ask for local guides.','Local guide and access fees paid in the village (small)','A deep crater lake near Kumba, ringed by rainforest and known for fish found nowhere else. Local guides lead walks and canoe trips. This deep crater lake is ringed by rainforest and is home to fish found nowhere else. Respect local customs and ask before swimming.'),
  ('Pangong Lake','pangong-lake','Lake','India','Ladakh','Pangong',33.75,78.67,'May to September','Sunrise and sunset; May to September, after acclimatising in Leh','Fly to Leh, then drive about 5-7 hours via Chang La pass. An Inner Line Permit is required and can be arranged online or in Leh.','Permit fees are small (roughly INR 400-600 in total) (approximate; confirm before you go)','A high-altitude lake in the Himalayas whose water shifts between blue, green and grey through the day. Permits are required and the altitude demands acclimatisation. The lake''s colour shifts between blue, green and grey through the day, and part of it lies across the border in Tibet. At over 4,200 metres, altitude sickness is possible.'),
  ('Amazon Rainforest','amazon-rainforest','Forest','Brazil','Amazonas','Manaus',-3.119,-60.0217,'June to November (drier months)','Sunrise and sunset boat trips; June to November for walking trails','Fly to Manaus (MAO). River lodges and tours leave from the port, and the Meeting of the Waters is a short boat trip away.','Tour and lodge prices vary (lodges often cost roughly US$100-300 per night) (approximate; confirm before you go)','The largest tropical rainforest on Earth, with rivers, wildlife and Indigenous communities. Many visitors explore by boat or jungle lodge from Manaus. Rivers, flooded forest and wildlife can be explored by boat and trail with local guides. Bring insect repellent and respect Indigenous communities and their rules.'),
  ('Black Forest','black-forest','Forest','Germany','Baden-Württemberg','Freiburg',48.0,8.2,'May to October','Morning mist; autumn colours','Take a train to Freiburg or Baden-Baden, then use buses or the Black Forest Railway to Triberg and Titisee.','Free to walk; the Triberg waterfalls cost roughly EUR 6 (approximate; confirm before you go)','A wooded mountain range of dark spruce and fir, known for hiking trails, lakes such as Titisee and traditional villages. Cuckoo clocks and cherry cake are local traditions. Dark spruce forests, lakes, cuckoo clocks and cherry cake define the region. The Schluchsee and Feldberg areas have long hiking trails.'),
  ('Daintree Rainforest','daintree-rainforest','Forest','Australia','Queensland','Daintree',-16.17,145.418,'May to September','Morning for bird and wildlife activity; May to September is the dry season','Drive 2 hours from Cairns to the Daintree River cable ferry, then 35 km further to Cape Tribulation.','The ferry costs roughly AUD 30-35 per car return; tours and boardwalks vary (approximate; confirm before you go)','One of the oldest rainforests in the world, meeting the Great Barrier Reef at Cape Tribulation. Rare plants, cassowaries and river cruises are highlights. The rainforest meets the Great Barrier Reef at Cape Tribulation. Cassowaries are dangerous if approached, so keep your distance and never feed them.'),
  ('Bwindi Impenetrable Forest','bwindi-impenetrable-forest','Forest','Uganda','Kanungu','Buhoma',-1.05,29.67,'June to August and December to February','Early morning start; treks last from 2 to 8 hours','Fly to Entebbe, Kigali or Kihihi. The road from Kampala takes about 8-10 hours. Trekking starts from Buhoma, Ruhija, Rushaga or Nkuringo.','A gorilla permit costs roughly US$800 for foreigners; confirm with the Uganda Wildlife Authority (approximate; confirm before you go)','An ancient mountain rainforest that shelters around half of the world''s mountain gorillas. Visits are strictly permit-controlled and led by trained guides. This ancient forest shelters about half of the world''s mountain gorillas. Visitors must be healthy, keep a safe distance and follow ranger instructions.'),
  ('Hoh Rain Forest','hoh-rain-forest','Forest','United States','Washington','Olympic National Park',47.86,-123.934,'July to September','Early morning for light and fewer people; spring for fresh moss','Drive about 3.5 hours from Seattle via the Olympic Peninsula to the Hoh Rain Forest Visitor Center.','About US$30 per vehicle for Olympic National Park (approximate; confirm before you go)','A temperate rainforest draped in moss, with giant spruce and hemlock trees. Short loop trails make it easy to walk among the old growth. The Hall of Mosses and Spruce Nature Trail are short loops through moss-draped trees. It is one of the wettest places in the continental US.'),
  ('Bialowieza Forest','bialowieza-forest','Forest','Poland','Podlaskie','Bialowieza',52.7,23.87,'May to September','Spring or summer mornings; winter for bison viewing','Take a train to Hajnowka and a bus to Bialowieza, about 3 hours from Warsaw. Guided tours enter the Strict Reserve.','Entry to the Strict Reserve requires a guide (small fee per group)','One of the last primeval lowland forests in Europe, on the Poland-Belarus border and home to wild European bison. Guided walks are available. The forest straddles the border with Belarus and has the largest free-living population of European bison. Check border and access rules before travelling.'),
  ('Arashiyama Bamboo Grove','arashiyama-bamboo-grove','Forest','Japan','Kyoto','Kyoto',35.0094,135.6672,'March to May and November to December','Before 8 am or after 4 pm for fewer people','Take the JR Sagano Line from Kyoto Station to Saga-Arashiyama (about 15 minutes), then walk about 10 minutes.','Free','A path through towering bamboo that creaks and sways in the wind, in western Kyoto. Go early in the morning for quiet and soft light. The path creaks in the wind as tall stalks sway overhead. Nearby are Tenryu-ji Temple and the Togetsukyo Bridge.'),
  ('Monteverde Cloud Forest','monteverde-cloud-forest','Forest','Costa Rica','Puntarenas','Monteverde',10.3,-84.8,'December to April','Early morning for birds; December to April is the dry season','About 4 hours (170 km) by road from San Jose via Tilaran, with a rough final stretch. Shuttles are available.','Reserve entry roughly US$25 per adult (approximate; confirm before you go)','A misty mountain forest rich in orchids, hummingbirds and, with luck, the resplendent quetzal. Hanging bridges and canopy walks give views from above. Hanging bridges and canopy walks give views from above the clouds. Hummingbirds, orchids and, with luck, the resplendent quetzal live here.'),
  ('Sinharaja Forest Reserve','sinharaja-forest-reserve','Forest','Sri Lanka','Sabaragamuwa','Deniyaya',6.4,80.4,'January to April','Dawn walks for birds; January to April has less rain','Drive from Colombo (about 4-5 hours) to the Deniyaya or Kalawana entrances. Local guides are required.','Foreign visitor fee roughly US$10-15 plus a guide fee (approximate; confirm before you go)','A rainforest reserve and UNESCO World Heritage Site with many endemic birds and plants. Leeches are common, so wear proper clothing and walk with a guide. It is a UNESCO World Heritage Site with many endemic birds and plants. Leeches are common, so wear leech socks and long trousers.'),
  ('Korup National Park','korup-national-park','Forest','Cameroon','Southwest','Mundemba',5.05,8.85,'December to February','Morning treks; dry season from December to February','Fly to Douala, then drive to Mundemba (6-8 hours, rough roads via Kumba). Arrange guides through the park office or a conservation organisation.','Park fees and porter or guide costs are arranged locally; contact the conservation service','One of Africa''s oldest and most biodiverse rainforests, with rare primates and thousands of plant species. Trekking is basic and needs a local guide and planning. This is one of Africa''s oldest and most diverse rainforests. Facilities are basic, and trips need careful planning and local guides.'),
  ('Redwood National Park','redwood-national-park','Forest','United States','California','Crescent City',41.2132,-124.0046,'May to September','Early morning mist; summer for fewer road closures','About 5 hours'' drive north of San Francisco on US-101, with scenic drives such as the Newton B. Drury Parkway.','Free for the national park; state park day-use fees apply at some sites (roughly US$8) (approximate; confirm before you go)','Home to the tallest trees on Earth, towering coast redwoods in misty forest by the Pacific. Quiet groves such as Lady Bird Johnson Grove have easy paths. Coast redwoods are the tallest trees on Earth, and the quietest groves are reached by short walks. Lady Bird Johnson Grove and Tall Trees Grove are favourites.'),
  ('Tsitsikamma Forest','tsitsikamma-forest','Forest','South Africa','Eastern Cape','Storms River',-33.9667,23.9,'October to April','Morning; October to April','Drive along the Garden Route, about 2 hours from Port Elizabeth, to the Storms River Mouth rest camp.','Conservation fee roughly ZAR 150-250 per adult (approximate; confirm before you go)','Ancient forest meeting the Indian Ocean, with swing bridges over the Storms River mouth. The Otter Trail is a famous multi-day coastal hike. A suspension bridge crosses the Storms River Mouth, and the Otter Trail is a famous multi-day coastal hike. Check weather and tides, and bring waterproofs.'),
  ('Danum Valley','danum-valley','Forest','Malaysia','Sabah','Lahad Datu',4.9667,117.8,'March to October','Dawn bird walks and evening night walks','Fly to Lahad Datu (LDU), then drive about 2 hours to the Danum Valley Field Centre. Stays are arranged through the field centre or its lodges.','Conservation fees and lodging packages, roughly US$100 or more per night (approximate; confirm before you go)','A protected lowland rainforest in Borneo with orangutans, pygmy elephants and giant trees. Canopy walkways and guided night walks show its wildlife. This lowland rainforest in Borneo is home to orangutans, pygmy elephants and giant trees. A canopy walkway gives a view of the treetops.'),
  ('Yakushima','yakushima','Forest','Japan','Kagoshima','Yakushima',30.3333,130.5,'April to June','Dawn walking; avoid typhoon season from August to October','Take a ferry or flight from Kagoshima (about 2-3.5 hours). Local buses go to trailheads, and Shiratani Unsuikyo is a walk of 1 to 3 hours.','Entrance fees roughly JPY 300-1,000 depending on the site (approximate; confirm before you go)','A mossy island forest of ancient cedars, some over a thousand years old, said to have inspired film forests. It is one of Japan''s wettest places. Ancient cedars, some over a thousand years old, stand in mossy forest and are said to have inspired film forests. It is one of Japan''s rainiest places, so bring rain gear.'),
  ('Taman Negara','taman-negara','Forest','Malaysia','Pahang','Kuala Tahan',4.35,102.4,'March to October','Early morning treks; March to October','Take a bus or train to Jerantut, then a van to Kuala Tembeling and a 3-hour boat up the Tembeling River, or drive and take a short boat to Kuala Tahan.','A small park fee (a few ringgit); some activities cost extra','One of the world''s oldest rainforests, with jungle trekking, river boats and a canopy walkway. Overnight wildlife hides give a chance to see animals. The canopy walkway, jungle treks and river trips show a rainforest said to be more than 130 million years old. Overnight wildlife hides give chances to see animals.'),
  ('Sequoia National Park','sequoia-national-park','Forest','United States','California','Three Rivers',36.4864,-118.5658,'May to September','Morning; spring for wildflowers; summer for open roads','Drive about 4 hours from Los Angeles or 3.5 hours from San Francisco via the Generals Highway. Snow chains may be required in winter.','About US$35 per vehicle (approximate; confirm before you go)','Groves of giant sequoias, the largest trees on Earth by volume, including the General Sherman Tree. The Giant Forest has easy trails among the trunks. The Giant Forest holds giant sequoias, the largest trees on Earth by volume, including the General Sherman Tree. Trails of different lengths wander among the trunks.'),
  ('Machu Picchu','machu-picchu','Culture','Peru','Cusco','Aguas Calientes',-13.1631,-72.545,'May to September','The first entry slots at around 6 am, for mist and fewer crowds','Take a train from Cusco or Ollantaytambo to Aguas Calientes (about 1.5-4 hours), then a bus up (25 minutes). Alternatively hike the Inca Trail with a licensed operator.','About PEN 152-200 (roughly US$40-55) with timed tickets; book online (approximate; confirm before you go)','A 15th-century Inca citadel high in the Andes, with terraces, temples and stonework fitted without mortar. Entry uses timed tickets, so book ahead. The citadel''s terraces, temples and stonework fit together without mortar. Altitude is about 2,400 metres, and the weather can change quickly.'),
  ('Angkor Wat','angkor-wat','Culture','Cambodia','Siem Reap','Siem Reap',13.4125,103.867,'November to February','Sunrise from the front pond, or late afternoon','Fly to Siem Reap (SAI), then take a tuk-tuk for about 20 minutes to the temples. Buy the Angkor Pass at the central ticket office.','About US$37 for 1 day, US$62 for 3 days or US$72 for 7 days (approximate; confirm before you go)','The largest religious monument in the world, a 12th-century Khmer temple in a vast ancient complex. Sunrise over its towers is the classic view. The complex also includes the Bayon and Ta Prohm, where tree roots grip the stone. Cover shoulders and knees to enter the temples.'),
  ('Petra','petra','Culture','Jordan','Ma''an','Wadi Musa',30.3285,35.4444,'March to May and September to November','Early morning for the Treasury; evening Petra by Night on selected days','Drive 3 hours from Amman or 2 hours from Aqaba to Wadi Musa. From the Visitor Centre, walk about 1.2 km through the Siq canyon.','About JOD 50 for one day (roughly US$70) for foreign visitors, with cheaper rates for those staying overnight in Jordan (approximate; confirm before you go)','A city carved into rose-coloured rock by the Nabataeans, reached through a narrow canyon. The Treasury is the famous facade, and a full day is worth allowing. The Treasury is the best-known facade, but the site covers many tombs and trails. Allow a full day and bring water and a hat.'),
  ('Colosseum','colosseum','Culture','Italy','Lazio','Rome',41.8902,12.4922,'April to June and September to October','The first slot of the day or the last hour before closing','Take Metro Line B to Colosseo. The Roman Forum and Palatine Hill are a short walk away, and skip-the-line tickets are sold online.','About EUR 16-18 for the Colosseum, Forum and Palatine Hill combined (approximate; confirm before you go)','Rome''s great Roman amphitheatre, built nearly 2,000 years ago to host public spectacles. Timed tickets cut queues, and early morning is quieter. Built nearly 2,000 years ago, it once held tens of thousands of spectators. Underground and arena-floor tours give extra access.'),
  ('Taj Mahal','taj-mahal','Culture','India','Uttar Pradesh','Agra',27.1751,78.0421,'October to March','Sunrise; the site is closed on Fridays','Take a train from Delhi to Agra (about 2-3 hours on the Gatimaan Express). From the car park, walk or take an electric bus, because petrol vehicles are not allowed near the monument.','About INR 1,300 for foreign visitors including the main mausoleum (approximate; confirm before you go)','A white marble mausoleum built in the 17th century beside the Yamuna River. It looks different at sunrise, and it is closed to visitors on Fridays. The white marble mausoleum was built in the 17th century beside the Yamuna River. Large bags and food are restricted, so travel light.'),
  ('Great Wall at Mutianyu','great-wall-at-mutianyu','Culture','China','Beijing','Huairou',40.4319,116.5704,'April to October','Early morning for fewer crowds; autumn for colours','About 70 km (1.5 hours) north of Beijing by tour bus or private car. A cable car or chairlift lifts you from the visitor centre to the wall.','Entry roughly CNY 40-45 plus a cable car of about CNY 120 (approximate; confirm before you go)','A well-restored section of the Great Wall with watchtowers along forested ridges north of Beijing. A cable car and toboggan run are available. This well-restored section has watchtowers along forested ridges. A toboggan run brings you down.'),
  ('Oia','oia','Culture','Greece','South Aegean','Santorini',36.4618,25.3753,'April to October','Sunrise for quiet blue-hour streets; the sunset at the castle ruins is very crowded','Fly to Santorini (JTR) or take a ferry from Piraeus or Athens (5-8 hours). A bus from Fira to Oia takes about 25 minutes.','Free to walk around the village','A clifftop village of white houses and blue-domed churches above the Aegean caldera. It is famous for its sunsets and gets very crowded in the evening. White houses, blue-domed churches and windmills overlook the caldera. Narrow lanes get very busy at sunset, so go early or stay overnight.'),
  ('Chichen Itza','chichen-itza','Culture','Mexico','Yucatan','Tinum',20.6843,-88.5678,'November to March','At opening time, before the heat and tour buses','Drive 2.5 hours from Merida or 2.5-3 hours from Cancun. ADO buses go to Chichen Itza, and many tours run from both cities.','Roughly MXN 600-700 for foreign visitors, combining state and federal fees (approximate; confirm before you go)','A major Maya city with the stepped El Castillo pyramid at its heart. Arrive at opening time to beat the heat and the crowds. El Castillo''s staircases line up to create a serpent shadow at the equinoxes. Climbing the pyramids is not allowed.'),
  ('Alhambra','alhambra','Culture','Spain','Andalusia','Granada',37.176,-3.5881,'March to May and September to October','The morning slot for the Nasrid Palaces; sunset from the Mirador de San Nicolas','Walk or take the local bus from central Granada to the entrance. Timed tickets are bought online and often sell out weeks ahead.','About EUR 19 for the general ticket (approximate; confirm before you go)','A hilltop palace and fortress of the Nasrid dynasty, famous for carved plaster and tilework. Tickets sell out, so book well ahead. The palace and gardens show carved plaster, tilework and water features. The Nasrid Palaces have a fixed entry time on your ticket.'),
  ('Hagia Sophia','hagia-sophia','Culture','Turkey','Istanbul','Istanbul',41.0086,28.9802,'April to May and September to November','Early morning or evening; avoid Friday midday prayers','Take the T1 tram to Sultanahmet. The mosque is beside the Blue Mosque, and foreign visitors use a separate entrance route.','Since 2024 foreign visitors pay about EUR 25; entry is free for Turkish citizens (approximate; confirm before you go)','A 6th-century building with a vast dome in Istanbul''s old city, once a cathedral and now a mosque. Dress modestly and expect busy queues. Built in the 6th century, it has a vast dome and Byzantine mosaics. Dress modestly, and expect queues and restricted access during prayer times.'),
  ('Fes el-Bali','fes-el-bali','Culture','Morocco','Fes-Meknes','Fes',34.0645,-4.973,'March to May and September to November','Early morning for quiet lanes; spring or autumn','Fly to Fes-Saiss (FEZ) or take a train from Casablanca or Marrakech. Enter through Bab Boujloud, with taxis to the gate.','Free to wander; madrasa and museum entries cost roughly MAD 20-70 (approximate; confirm before you go)','The old walled medina of Fes, a maze of lanes, tanneries and medieval madrasas. Hire a licensed guide the first time to find your way. A maze of lanes, tanneries and medieval madrasas. Hire a licensed guide for the first visit, and agree on prices before you start.'),
  ('Great Zimbabwe','great-zimbabwe','Culture','Zimbabwe','Masvingo','Masvingo',-20.267,30.933,'May to October','Morning for cooler climbs; May to October is the dry season','About 30 km (30 minutes) from Masvingo town by road. From Harare, it is about 300 km (4 hours) by road.','Roughly US$15-20 for foreign visitors (approximate; confirm before you go)','The stone ruins of a medieval city that gave Zimbabwe its name, with a hilltop complex and the Great Enclosure. It was the centre of a powerful trading kingdom. The hilltop complex and the Great Enclosure were the centre of a powerful trading kingdom. The site gave modern Zimbabwe its name.'),
  ('Foumban Royal Palace','foumban-royal-palace','Culture','Cameroon','West','Foumban',5.727,10.898,'November to March','Morning; December is when the Nguon festival is held, usually every two years','Drive about 5 hours (300 km) from Douala or Yaounde. Shared taxis and buses run to Foumban, and the palace is in the town centre.','A small entry fee for the palace and museum (a few thousand CFA francs)','The palace of the Bamoun kings, built in the early 1900s, with a museum of royal art and history. Foumban is known for craftsmen working in bronze and wood. The palace of the Bamoun kings holds royal art, thrones and history. Craftsmen in the town work in bronze, wood and cloth.'),
  ('Fushimi Inari Shrine','fushimi-inari-shrine','Culture','Japan','Kyoto','Kyoto',34.9671,135.7727,'March to May and October to November','Before 7 am or after dusk','Take the JR Nara Line to Inari Station (5 minutes from Kyoto Station) or the Keihan line to Fushimi-Inari. The shrine is beside the station.','Free; open 24 hours (approximate; confirm before you go)','A shrine famous for thousands of vermilion torii gates winding up a forested hill. It is open all day, and early or late visits are far quieter. Thousands of vermilion torii gates wind up the forested hill. The full loop takes 2-3 hours, but short sections already give the classic views.'),
  ('Pyramids of Giza','pyramids-of-giza','Culture','Egypt','Giza','Giza',29.9792,31.1342,'October to April','At opening time, to beat the heat and crowds; an evening sound-and-light show runs after dark','Take a taxi or ride-hailing car from central Cairo (30-60 minutes). The Grand Egyptian Museum is nearby, and entry is through the Giza Plateau gates.','Roughly EGP 700-900 for the plateau, with separate tickets to enter some pyramids (approximate; confirm before you go)','The last surviving wonder of the ancient world, built over 4,500 years ago as royal tombs beside the Sphinx. Start early to avoid the midday heat. The last surviving wonder of the ancient world stands beside the Sphinx. Agree on prices before camel or horse rides, and bring water and sun protection.')
  ) as v(name, slug, category, country, region, city, latitude, longitude, best_season, best_time, access_info, entry_fee, description);

  -- 1) Upgrade places from the earlier shorter seed that still have the placeholder text (never touches edited places).
  update public.places p
     set description = s.description, access_info = s.access_info, entry_fee = s.entry_fee,
         best_season = s.best_season, best_time = s.best_time, country = s.country, region = s.region, city = s.city
    from seed_places s
   where p.slug = s.slug and p.created_by = owner
     and p.access_info = 'Check access, opening times and conditions locally before travelling.'
     and p.entry_fee = 'Varies. Check before you go.';

  -- 2) Add places that are missing, skipping anything you added yourself (even if named a little differently).
  insert into public.places (name, slug, category, country, region, city, latitude, longitude, best_season, best_time,
                             access_info, entry_fee, description, status, created_by)
  select v.name, v.slug, v.category, v.country, v.region, v.city, v.latitude, v.longitude, v.best_season, v.best_time,
         v.access_info, v.entry_fee, v.description, 'draft', owner
    from seed_places v
   where not exists (
           select 1 from public.places p
            where p.slug = v.slug or p.slug like v.slug || '-%'
               or regexp_replace(lower(p.name), '[^a-z0-9]+', '', 'g') = regexp_replace(lower(v.name), '[^a-z0-9]+', '', 'g'))
     and not exists (
           select 1 from (values
             ('victoria-falls', '%victoria%'),
             ('lake-malawi', '%malawi%'),
             ('mount-cameroon', '%cameroon%'),
             ('anse-source-d-argent', '%source%argent%'),
             ('bwindi-impenetrable-forest', '%bwindi%')
           ) as skip(slug, pattern)
           join public.places p on p.name ilike skip.pattern
          where skip.slug = v.slug)
  on conflict (slug) do nothing;
end $$;
